# Setup
title:               Hobo by choice
tagline:             'My digital nomad experience travelling around Japan'
description:         'My digital nomad experience travelling around Japan'
url:                 https://hobo.szabo-simon.hu
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Szabo-Simon
  url:               https://twitter.com/torin42
  email:             mark@szabo-simon.hu

# Gems
plugins:
  - jekyll-paginate

collections:
- images

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
