# Setup
title:               マークン
tagline:             'Japan and tech'
description:         'Japan and tech'
url:                 https://m.szabo.jp
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Szabo
  url:               https://twitter.com/torin42
  email:             mark@szabo.jp

# Gems
plugins:
  - jekyll-paginate

collections:
- images

# Custom vars
version:             1.1.0
